## code to prepare `countries` dataset goes here

country_abbreviations_vector <- c(
  "",
  "AF",
  "AL",
  "DZ",
  "AD",
  "AO",
  "AI",
  "AQ",
  "AG",
  "AR",
  "AM",
  "AW",
  "AU",
  "AT",
  "AZ",
  "BS",
  "BH",
  "BD",
  "BB",
  "BY",
  "BE",
  "BZ",
  "BJ",
  "BM",
  "BT",
  "BO",
  "BA",
  "BW",
  "BV",
  "BR",
  "IO",
  "BN",
  "BG",
  "BF",
  "BI",
  "KH",
  "CM",
  "CA",
  "CV",
  "KY",
  "CF",
  "TD",
  "CL",
  "CN",
  "CX",
  "CC",
  "CO",
  "KM",
  "CD",
  "CK",
  "CR",
  "HR",
  "CI",
  "CU",
  "CY",
  "CZ",
  "DK",
  "DJ",
  "DM",
  "DO",
  "EC",
  "EG",
  "SV",
  "GQ",
  "ER",
  "EE",
  "ET",
  "FK",
  "FO",
  "FJ",
  "FI",
  "FR",
  "GF",
  "PF",
  "TF",
  "GA",
  "GM",
  "GE",
  "DE",
  "GH",
  "GI",
  "GB",
  "GR",
  "GL",
  "GD",
  "GP",
  "GT",
  "GG",
  "GN",
  "GW",
  "GY",
  "HT",
  "HM",
  "VA",
  "HN",
  "HK",
  "HU",
  "IS",
  "IN",
  "ID",
  "IR",
  "IQ",
  "IE",
  "IM",
  "IL",
  "IT",
  "JM",
  "JP",
  "JE",
  "JO",
  "KZ",
  "KE",
  "KI",
  "KP",
  "KR",
  "XK",
  "KW",
  "KG",
  "LA",
  "LV",
  "LB",
  "LS",
  "LR",
  "LY",
  "LI",
  "LT",
  "LU",
  "MO",
  "MK",
  "MG",
  "MW",
  "MY",
  "MV",
  "ML",
  "MT",
  "MQ",
  "MR",
  "MU",
  "YT",
  "MX",
  "MD",
  "MC",
  "MN",
  "MS",
  "MA",
  "MZ",
  "MM",
  "NA",
  "NR",
  "NP",
  "NL",
  "AN",
  "NC",
  "NZ",
  "NI",
  "NE",
  "NG",
  "NU",
  "NF",
  "NO",
  "OM",
  "PK",
  "PW",
  "PS",
  "PA",
  "PG",
  "PY",
  "PE",
  "PH",
  "PN",
  "PL",
  "PT",
  "QA",
  "RE",
  "RO",
  "RU",
  "RW",
  "SH",
  "KN",
  "LC",
  "PM",
  "VC",
  "WS",
  "SM",
  "ST",
  "SA",
  "SN",
  "CS",
  "SC",
  "SL",
  "SG",
  "SK",
  "SI",
  "SB",
  "SO",
  "ZA",
  "GS",
  "ES",
  "LK",
  "SD",
  "SR",
  "SJ",
  "SZ",
  "SE",
  "CH",
  "SY",
  "TW",
  "TJ",
  "TZ",
  "TH",
  "TL",
  "TG",
  "TK",
  "TO",
  "TT",
  "TN",
  "TR",
  "TM",
  "TC",
  "TV",
  "UG",
  "UA",
  "AE",
  "US",
  "UM",
  "UY",
  "UZ",
  "VU",
  "VE",
  "VN",
  "VG",
  "WF",
  "EH",
  "YE",
  "ZM",
  "ZW"
)

countries_vector <- c("Any",
                      "Afghanistan",
                      "Albania",
                      "Algeria",
                      "Andorra",
                      "Angola",
                      "Anguilla",
                      "Antarctica",
                      "Antigua and Barbuda",
                      "Argentina",
                      "Armenia",
                      "Aruba",
                      "Australia",
                      "Austria",
                      "Azerbaijan",
                      "Bahamas",
                      "Bahrain",
                      "Bangladesh",
                      "Barbados",
                      "Belarus",
                      "Belgium",
                      "Belize",
                      "Benin",
                      "Bermuda",
                      "Bhutan",
                      "Bolivia",
                      "Bosnia and Herzegovina",
                      "Botswana",
                      "Bouvet Island",
                      "Brazil",
                      "British Indian Ocean Territory",
                      "Brunei Darussalam",
                      "Bulgaria",
                      "Burkina Faso",
                      "Burundi",
                      "Cambodia",
                      "Cameroon",
                      "Canada",
                      "Cape Verde",
                      "Cayman Islands",
                      "Central African Republic",
                      "Chad",
                      "Chile",
                      "China",
                      "Christmas Island",
                      "Cocos (Keeling) Islands",
                      "Colombia",
                      "Comoros",
                      "Congo, The Democratic Republic of the",
                      "Cook Islands",
                      "Costa Rica",
                      "Croatia",
                      "Ctte D'Ivoire",
                      "Cuba",
                      "Cyprus",
                      "Czech Republic",
                      "Denmark",
                      "Djibouti",
                      "Dominica",
                      "Dominican Republic",
                      "Ecuador",
                      "Egypt",
                      "El Salvador",
                      "Equatorial Guinea",
                      "Eritrea",
                      "Estonia",
                      "Ethiopia",
                      "Falkland Islands (Malvinas)",
                      "Faroe Islands",
                      "Fiji",
                      "Finland",
                      "France",
                      "French Guiana",
                      "French Polynesia",
                      "French Southern Territories",
                      "Gabon",
                      "Gambia",
                      "Georgia",
                      "Germany",
                      "Ghana",
                      "Gibraltar",
                      "Great Britain",
                      "Greece",
                      "Greenland",
                      "Grenada",
                      "Guadeloupe",
                      "Guatemala",
                      "Guernsey",
                      "Guinea",
                      "Guinea-Bissau",
                      "Guyana",
                      "Haiti",
                      "Heard Island and McDonald Islands",
                      "Holy See (Vatican City State)",
                      "Honduras",
                      "Hong Kong",
                      "Hungary",
                      "Iceland",
                      "India",
                      "Indonesia",
                      "Iran, Islamic Republic of",
                      "Iraq",
                      "Ireland",
                      "Isle Of Man",
                      "Israel",
                      "Italy",
                      "Jamaica",
                      "Japan",
                      "Jersey",
                      "Jordan",
                      "Kazakhstan",
                      "Kenya",
                      "Kiribati",
                      "Korea, Democratic People's Republic of",
                      "Korea, Republic of",
                      "Kosovo",
                      "Kuwait",
                      "Kyrgyzstan",
                      "Lao People's Democratic Republic",
                      "Latvia",
                      "Lebanon",
                      "Lesotho",
                      "Liberia",
                      "Libyan Arab Jamahiriya",
                      "Liechtenstein",
                      "Lithuania",
                      "Luxembourg",
                      "Macao",
                      "Macedonia, The Former Yugoslav Republic of",
                      "Madagascar",
                      "Malawi",
                      "Malaysia",
                      "Maldives",
                      "Mali",
                      "Malta",
                      "Martinique",
                      "Mauritania",
                      "Mauritius",
                      "Mayotte",
                      "Mexico",
                      "Moldova, Republic of",
                      "Monaco",
                      "Mongolia",
                      "Montserrat",
                      "Morocco",
                      "Mozambique",
                      "Myanmar",
                      "Namibia",
                      "Nauru",
                      "Nepal",
                      "Netherlands",
                      "Netherlands Antilles",
                      "New Caledonia",
                      "New Zealand",
                      "Nicaragua",
                      "Niger",
                      "Nigeria",
                      "Niue",
                      "Norfolk Island",
                      "Norway",
                      "Oman",
                      "Pakistan",
                      "Palau",
                      "Palestinian Territory, Occupied",
                      "Panama",
                      "Papua New Guinea",
                      "Paraguay",
                      "Peru",
                      "Philippines",
                      "Pitcairn",
                      "Poland",
                      "Portugal",
                      "Qatar",
                      "Reunion",
                      "Romania",
                      "Russian Federation",
                      "Rwanda",
                      "Saint Helena",
                      "Saint Kitts and Nevis",
                      "Saint Lucia",
                      "Saint Pierre and Miquelon",
                      "Saint Vincent and the Grenadines",
                      "Samoa",
                      "San Marino",
                      "Sao Tome and Principe",
                      "Saudi Arabia",
                      "Senegal",
                      "Serbia and Montenegro",
                      "Seychelles",
                      "Sierra Leone",
                      "Singapore",
                      "Slovakia",
                      "Slovenia",
                      "Solomon Islands",
                      "Somalia",
                      "South Africa",
                      "South Georgia and the South Sandwich Islands",
                      "Spain",
                      "Sri Lanka",
                      "Sudan",
                      "Suriname",
                      "Svalbard and Jan Mayen",
                      "Swaziland",
                      "Sweden",
                      "Switzerland",
                      "Syrian Arab Republic",
                      "Taiwan",
                      "Tajikistan",
                      "Tanzania, United Republic of",
                      "Thailand",
                      "Timor-Leste",
                      "Togo",
                      "Tokelau",
                      "Tonga",
                      "Trinidad and Tobago",
                      "Tunisia",
                      "Turkey",
                      "Turkmenistan",
                      "Turks and Caicos Islands",
                      "Tuvalu",
                      "Uganda",
                      "Ukraine",
                      "United Arab Emirates",
                      "United States",
                      "United States Minor Outlying Islands",
                      "Uruguay",
                      "Uzbekistan",
                      "Vanuatu",
                      "Venezuela",
                      "Viet Nam",
                      "Virgin Islands, British",
                      "Wallis and Futuna",
                      "Western Sahara",
                      "Yemen",
                      "Zambia",
                      "Zimbabwe")
countries<-country_abbreviations_vector
names(countries) <- countries_vector
usethis::use_data(countries, overwrite = TRUE)
